Starting Natnet3.x interface at 1234567
initial positions are [array([ 0.48387097, -1.87903226,  0.5       ])]
NAT_CONNECT to Motive with 4 1 0 0
Exception in thread Thread-4 (__data_thread_function):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adriandelser/Desktop/ENAC/flighthouse/real_flights/NatNetClient.py", line 1588, in __data_thread_function
    message_id = self.__process_message( data , print_level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adriandelser/Desktop/ENAC/flighthouse/real_flights/NatNetClient.py", line 1616, in __process_message
    offset_tmp, mocap_data = self.__unpack_mocap_data( data[offset:], packet_size, major, minor )
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adriandelser/Desktop/ENAC/flighthouse/real_flights/NatNetClient.py", line 820, in __unpack_mocap_data
    rel_offset, marker_set_data =self.__unpack_marker_set_data(data[offset:], (packet_size - offset),major, minor)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adriandelser/Desktop/ENAC/flighthouse/real_flights/NatNetClient.py", line 489, in __unpack_marker_set_data
    trace_mf( "Model Name      : ", model_name.decode( 'utf-8' ) )
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte
[0. 0. 0.]
[INFO] tello.py - 676 - Send command: 'takeoff'